In [50]:
import numpy as np
import pandas as pd

In [51]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [52]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [53]:
def initialize_parameters(layer_dims): #here we give model architechture number of nodes layer wise in list and it returns all weights and bias

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters

In [54]:
parameters=initialize_parameters([2,2,1])

In [55]:
def linear_forward(A_prev, W, b): #it is product of output from previous layer with wight and add bias

  Z = np.dot(W.T, A_prev) + b

  return Z

In [69]:
# this is doing Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev #returning previous output and output because needed for back prop calc

In [57]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [58]:
y_hat

array([[0.32]])

In [59]:
def update_parameters(parameters,y,y_hat,A1,X):
  g1=(0.001 * 2 * (y - y_hat)*A1[0][0])
  g2=(0.001 * 2 * (y - y_hat)*A1[1][0])
  g3=(0.001 * 2 * (y - y_hat))
  g4=(0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  g5=(0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  g6=(0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])
  g7=(0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  g8=(0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  g9=(0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])
  parameters['W2'][0][0] = parameters['W2'][0][0] + g1#(0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + g2#(0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + g3#(0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + g4#(0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + g5#(0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + g6#(0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + g7#(0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + g8#(0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + g9#(0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

  #campusx updated the weights as it find gradient but for 1 input I updated all weights together not like one updated weight used for calculatn of old one

In [60]:
update_parameters(parameters,y,y_hat,A1,X)

In [61]:
#when updating weights as one (i think this one is more correct, check or confirm this up)
parameters

{'W1': array([[0.105888, 0.105888],
        [0.105888, 0.105888]]),
 'b1': array([[0.000736],
        [0.000736]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [62]:
#what campusx did
parameters

{'W1': array([[0.105888, 0.105888],
        [0.105888, 0.105888]]),
 'b1': array([[0.000736],
        [0.000736]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [63]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.105888 0.105888]
 [0.105888 0.105888]]
b1:  [[0.000736]
 [0.000736]]
----------------------------------------
A1:  [[1.694944]
 [1.694944]]
****************************************
A1:  [[1.694944]
 [1.694944]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.49804412]]
****************************************


In [64]:
update_parameters(parameters,y,y_hat,A1,X)

In [65]:
parameters

{'W1': array([[0.11293295, 0.11494579],
        [0.11293295, 0.11494579]]),
 'b1': array([[0.00174242],
        [0.00174242]]),
 'W2': array([[0.12703713],
        [0.12703713]]),
 'b2': array([[0.13604104]])}

In [66]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X, parameters)

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[ 6]
 [10]]
W1:  [[0.11293295 0.11494579]
 [0.11293295 0.11494579]]
b1:  [[0.00174242]
 [0.00174242]]
----------------------------------------
A1:  [[1.8086696 ]
 [1.84087508]]
****************************************
A1:  [[1.8086696 ]
 [1.84087508]]
W2:  [[0.12703713]
 [0.12703713]]
b2:  [[0.13604104]]
----------------------------------------
A2:  [[0.59966871]]
****************************************


{'W1': array([[0.12116546, 0.12866664],
        [0.12116546, 0.12866664]]),
 'b1': array([[0.00311451],
        [0.00311451]]),
 'W2': array([[0.14657196],
        [0.1469198 ]]),
 'b2': array([[0.15772046]])}

In [67]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[ 5]
 [12]]
W1:  [[0.12116546 0.12866664]
 [0.12116546 0.12866664]]
b1:  [[0.00311451]
 [0.00311451]]
----------------------------------------
A1:  [[2.06292732]
 [2.19044743]]
****************************************
A1:  [[2.06292732]
 [2.19044743]]
W2:  [[0.14657196]
 [0.1469198 ]]
b2:  [[0.15772046]]
----------------------------------------
A2:  [[0.78190784]]
****************************************


{'W1': array([[0.13027944, 0.15054019],
        [0.13030107, 0.1505921 ]]),
 'b1': array([[0.0049373 ],
        [0.00494163]]),
 'W2': array([[0.1722269],
        [0.1741606]]),
 'b2': array([[0.18659679]])}

In [79]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 10

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.409563722056774
Epoch -  2 Loss -  18.915978403231257
Epoch -  3 Loss -  10.52545812042183
Epoch -  4 Loss -  3.945608517868013
Epoch -  5 Loss -  1.5057565023949806
Epoch -  6 Loss -  1.1802354966225144
Epoch -  7 Loss -  1.2297421058817344
Epoch -  8 Loss -  1.2709349027067218
Epoch -  9 Loss -  1.2878911275864011
Epoch -  10 Loss -  1.2945367346256915


{'W1': array([[0.24709081, 0.41156051],
        [0.2548656 , 0.43654761]]),
 'b1': array([[0.02768783],
        [0.02962556]]),
 'W2': array([[0.43140732],
        [0.50962022]]),
 'b2': array([[0.51210776]])}

In [78]:
 #now implementing same thing using keras

In [80]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [81]:
model=Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [82]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [85]:
model.get_weights()

[array([[-0.29891628,  0.18421328],
        [ 0.53691804,  1.205268  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.87172425],
        [-1.4129376 ]], dtype=float32),
 array([0.], dtype=float32)]

In [120]:
new_weights=[np.array([[0.1,  0.1],
        [ 0.1,0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[ 0.1],
        [0.1 ]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [125]:
model.set_weights(new_weights)

In [129]:
model.get_weights()

[array([[0.37851873, 0.37851873],
        [0.37269378, 0.37269378]], dtype=float32),
 array([0.2785926, 0.2785926], dtype=float32),
 array([[0.37932637],
        [0.37932637]], dtype=float32),
 array([0.20835969], dtype=float32)]

In [127]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [128]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,verbose=1,epochs=80,batch_size=1)

Epoch 1/80
4/4 [==============================] - 1s 4ms/step - loss: 27.8792
Epoch 2/80
4/4 [==============================] - 0s 4ms/step - loss: 27.5657
Epoch 3/80
4/4 [==============================] - 0s 4ms/step - loss: 27.2586
Epoch 4/80
4/4 [==============================] - 0s 3ms/step - loss: 26.8990
Epoch 5/80
4/4 [==============================] - 0s 3ms/step - loss: 26.5536
Epoch 6/80
4/4 [==============================] - 0s 4ms/step - loss: 26.2172
Epoch 7/80
4/4 [==============================] - 0s 3ms/step - loss: 25.8350
Epoch 8/80
4/4 [==============================] - 0s 3ms/step - loss: 25.4337
Epoch 9/80
4/4 [==============================] - 0s 4ms/step - loss: 25.0734
Epoch 10/80
4/4 [==============================] - 0s 3ms/step - loss: 24.6461
Epoch 11/80
4/4 [==============================] - 0s 4ms/step - loss: 24.2490
Epoch 12/80
4/4 [==============================] - 0s 3ms/step - loss: 23.7949
Epoch 13/80
4/4 [==============================] - 0s 4ms/ste

In [ ]:
#in keras it took more epochs to get to the loss that was achieved with mannual coding with very less epochs